### PR TITLE
Make ansible variables available in Vagrantfile

### PR DESCRIPTION
**Pull request by gnucifer**
Would be nice if vagrant vm configuration variables could be made available in Vagrantconfig. Also changed to koha directory path from being hard coded to config variable.

### CODE REVIEW

**Comment by tomascohen** [comment]
I like the idea. Let me wrap up my mind on the possible consequences on workflow change.

**Comment by gnucifer** [comment]
Found a problem, a hard coded Koha path is also found in the misc4dev scripts. Added ansible tasks to replace all instances of this path with the path set in koha_dir.

**Comment by gnucifer** [comment]
About the last commit, tried to be smart and only force clone when path is non standard, but this causes problem if changes back to standard path. I agree it would perhaps be better to change the misc4dev scripts, but just figured it required a lot more coordination than this simple band aid. Perhaps it can be removed once the change has been done in misc4dev.

**Comment by tomascohen** [comment]
@gnucifer I provided a couple patches for koha-misc4dev so some stuff can be parametrized. We can fix it there.

I've filed an issue on kohadevbox specifically for having the ansible variables available in Vagrantfile. Can you separate generate a pull request with that part specifically, and use a subject like "Issue #191:..."  I think that could have an interesting value.

**Pull request closed without merging**
